### ISSUE TITLE
How to add code to highlight?

### ISSUE THREAD

**Issue by DC921115** [surmon-china/ngx-quill-editor#12]
I want to paste some code,how to add code to highlight?

**Comment by surmon-china** [comment]
```javascript  
// import in your entry
import hljs from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'

// and set option
editorOption: {
  modules: {
    syntax: {
      highlight: text => window.hljs.highlightAuto(text).value
      // or
      /*
      highlight(text) {
        const result = window.hljs.highlightAuto(text)
        return result.value
      }
      */
    }
  },
  theme: 'snow'
}
```

https://quilljs.com/docs/modules/syntax/
https://github.com/quilljs/quill/blob/develop/docs/docs/modules/syntax.md
https://github.com/quilljs/quill/blob/develop/modules/syntax.js#L68
https://github.com/quilljs/quill/blob/develop/modules/syntax.js#L41

**Comment by DC921115** [comment]
thanks

**Comment by DC921115** [comment]
I import  the highLight.js ; and set the options ,
this is a error : 'hljs' does not exist on type 'Window'.
@surmon-china
