### ISSUE TITLE
need to register ImageResize moudule ?

### ISSUE THREAD

**Issue by kudsyf** [surmon-china/ngx-quill-editor#15]
i need to add the functionality of image resize to the editor, how ?

**Comment by surmon-china** [comment]
https://github.com/kensnyder/quill-image-resize-module

https://github.com/kensnyder/quill-image-drop-module

**Comment by kudsyf** [comment]
am getting 

```
image-resize.min.js:1 Uncaught TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (image-resize.min.js:1)
```

**Comment by EonchGao** [comment]
> am getting
> 
> ```
> image-resize.min.js:1 Uncaught TypeError: Cannot read property 'imports' of undefined
>     at Object.<anonymous> (image-resize.min.js:1)
> ```

Can you solve it?
