### ISSUE TITLE
not find css 

### ISSUE THREAD

**Issue by Acumes** [surmon-china/ngx-quill-editor#16]
E:/angular2/my-app2/node_modules/ng2-quill-editor/quillEditor.component.ts (23,5): Cannot find name 'require'.
this is source code quillEditor.component.ts
 styles: [
    require('quill/dist/quill.core.css'),
    require('quill/dist/quill.snow.css'),
    require('quill/dist/quill.bubble.css')
  ],

**Comment by surmon-china** [comment]
@Acumes 

You should try the  v2.0.2, it was reslove the issue.

https://github.com/surmon-china/ngx-quill-editor/blob/master/quillEditor.component.ts#L21
