### ISSUE TITLE
quill图片上传后为base64格式

### ISSUE THREAD

**Issue by lirunkai** [surmon-china/ngx-quill-editor#18]
怎么能先上传到七牛这些第三方,是需要修改ngx-quill-editor的源文件么

**Comment by lirunkai** [comment]
ngx-quill-editor,QuillEditorComponent里面添加
` // 写入图片
  writeImg(currentValue: any) {
    this.content = currentValue;

    if (this.quillEditor) {
      if (currentValue) {
        this.quillEditor.insertEmbed(10, 'image', currentValue);
        return;
      }
      this.quillEditor.setText('');
    }
  }`

可以实现效果,想问下, 在ngOnChanges里面或者有没有事件触发这个图片上传

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor/issues/21

**Comment by surmon-china** [comment]
https://github.com/surmon-china/angular-admin/tree/master/src/app/theme/components/baPictureUploader
