### ISSUE TITLE
Toolbar - how do you remove link,image,video

### ISSUE THREAD

**Issue by john-lieb** [surmon-china/ngx-quill-editor#44]
Hi I am having trouble removing the link,image and video buttons

@Component({
    selector: 'app-notes',
    templateUrl: './notes.component.html',
    styleUrls: ['./notes.component.scss']
})
export class NotesComponent implements OnInit {
    editorValue: string;
    notes: any;
    modalRef: NgbModalRef;

    public editorConfig = {
    theme: 'bubble',
    placeholder: 'Add a note',
    modules: {
      toolbar: [
            ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
            ['blockquote', 'code-block'],
            [{ 'header': 1 }, { 'header': 2 }],               // custom button values
            [{ 'list': 'ordered' }, { 'list': 'bullet' }],
            [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
            [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
            [{ 'direction': 'rtl' }],                         // text direction
            [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
            [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
            [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
            [{ 'font': [] }],
            [{ 'align': [] }],
            ['clean']
            //['link', 'image','video']                                  
      ],
    }
   };

  html...
`<div class="notes">
            <div class="modal-header">
                <span>
                    <i class="fa fa-4x fa-pencil-square-o"></i>
                </span>
            </div>
            <div class="modal-body">
                <quill-editor [options]="editorConfig" [(ngModel)]="editorValue" (onEditorCreated)="setFocus($event)">
                </quill-editor>
            </div>
            <div class="modal-footer">
                <button type="button" (click)="onNotesSave(editorValue)" class="btn btn-primary notes__btn">Save</button>
            </div>
    </div>`
![image](https://user-images.githubusercontent.com/30803583/36586364-64fc7576-1879-11e8-92ef-0639714396a8.png)

Any help would be appreciated thank you.

**Comment by reenezden** [comment]
Hello, have you been able to fix this?

**Comment by john-lieb** [comment]
Hi @reenezden unfortunately not. I created a new angular 5 project. Started getting this error... ERROR in ./node_modules/ngx-quill-editor/index.ts
Module build failed: Error: /node_modules/ngx-quill-editor/index.ts is not part of the compilation output. Please check the other error messages for details.

I think its linked to this #31.

**Comment by john-lieb** [comment]
I ended up using https://github.com/KillerCodeMonkey/ngx-quill which works with Angular 5 and the toolbar configuration is almost the same.
